import type { Metadata } from "next";
import { Mulish, Alegreya, Alegreya_SC, Rozha_One } from "next/font/google";
import Nav from "@/components/Nav/Nav";

import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

const alegreyaSC = Alegreya_SC({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["400", "500", "700", "900"],
});

const rozhaOne = Rozha_One({
  subsets: ["latin"],
  variable: "--font-display-bold",
  weight: ["400"], // Rozha One only has 400
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mulish.variable} ${alegreya.variable} ${alegreyaSC.variable} ${rozhaOne.variable}`}
    >
      <body>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
