import type { Metadata } from "next";
import { Alegreya, Rozha_One } from "next/font/google";
import Nav from "@/components/ui/Nav/Nav";

import "./globals.css";

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

const rozhaOne = Rozha_One({
  subsets: ["latin"],
  variable: "--font-display-bold",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${alegreya.variable} ${rozhaOne.variable}`}>
      <body>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
