import type { Metadata } from "next";
import { Alegreya, Rozha_One } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import Nav from "@/components/ui/Nav/Nav";
import Footer from "@/components/ui/Footer/Footer";

import "./globals.css";

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

const rozhaOne = Rozha_One({
  subsets: ["latin"],
  variable: "--font-display-bold",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${alegreya.variable} ${rozhaOne.variable}`}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/jmm4bpu.css" />
      </head>
      <body>
        <Nav />
        <main>{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
